fichero = open("fichero.txt","w")
fichero.write("hola , mensaje cambiado")
fichero.close()
print("Texto aguardado")
fichero = open("fichero.txt","r")
texto = fichero.readline()
fichero.close()
print(texto)
print("fichero leido")